apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-nginx-ope-cache
  template:
    metadata:
      labels:
        app: laravel-nginx-ope-cache
    spec:
      containers:
        - name: laravel-nginx-ope-cache
          image: rencecaringal000/laravel_9_nginx_ope_cache
          ports:
            - containerPort: 9000
