apiVersion: v1
kind: Service
metadata:
  name: ormeco-service
spec:
  type: NodePort
  selector:
    app: ormeco-fullstack-laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
